# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
platform :ios, '8.0'

target 'TagPicture' do
   pod 'SwiftKeychainWrapper'
#target 'TagPicture' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#  use_frameworks!
#  pod 'SwiftKeychainWrapper'
# Pods for TagPicture

end
